apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oy5h46y2j-go 
  janus-idp.io/tekton: oy5h46y2j-go
  backstage.io/kubernetes-id: oy5h46y2j-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oy5h46y2j-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  