apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oy5h46y2j-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oy5h46y2j-go 
  name: oy5h46y2j-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oy5h46y2j-go 
